config/routes.rb
Rails.application.routes.draw do
  resources :ruby_win_sources
  root 'welcome#index'

end

app/models/ruby_win_source.rb
class RubyWinSource < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ruby_win_sources_controller.rb
class RubyWinSourcesController < ApplicationController
  before_action :set_ruby_win_source, only: [:show, :edit, :update, :destroy]

  # GET /ruby_win_sources
  # GET /ruby_win_sources.json
  def index
    @ruby_win_sources = RubyWinSource.all
  end

  # GET /ruby_win_sources/1
  # GET /ruby_win_sources/1.json
  def show
  end

  # GET /ruby_win_sources/new
  def new
    @ruby_win_source = RubyWinSource.new
  end

  # GET /ruby_win_sources/1/edit
  def edit
  end

  # POST /ruby_win_sources
  # POST /ruby_win_sources.json
  def create
    @ruby_win_source = RubyWinSource.new(ruby_win_source_params)

    respond_to do |format|
      if @ruby_win_source.save
        format.html { redirect_to @ruby_win_source, notice: 'Ruby win source was successfully created.' }
        format.json { render :show, status: :created, location: @ruby_win_source }
      else
        format.html { render :new }
        format.json { render json: @ruby_win_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ruby_win_sources/1
  # PATCH/PUT /ruby_win_sources/1.json
  def update
    respond_to do |format|
      if @ruby_win_source.update(ruby_win_source_params)
        format.html { redirect_to @ruby_win_source, notice: 'Ruby win source was successfully updated.' }
        format.json { render :show, status: :ok, location: @ruby_win_source }
      else
        format.html { render :edit }
        format.json { render json: @ruby_win_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ruby_win_sources/1
  # DELETE /ruby_win_sources/1.json
  def destroy
    @ruby_win_source.destroy
    respond_to do |format|
      format.html { redirect_to ruby_win_sources_url, notice: 'Ruby win source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ruby_win_source
      @ruby_win_source = RubyWinSource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ruby_win_source_params
      params.require(:ruby_win_source).permit(:name, :author, :url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ruby_win_sources_helper.rb
module RubyWinSourcesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Ramón Ledezma - Curriculum</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="css/mystyles.css">
	<%= csrf_meta_tags %>
</head>
<body class="scroll-area">

	<%= yield %>


	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="js/cbpAnimatedHeader.js"></script>
	<script type="text/javascript" src="js/classie.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			$('body').scrollspy({target: '.navbar-fixed-top', selector: '.spythis', offset:40}); 
		});
		$(document).on('click','.navbar-collapse.in',function(e) {
			if( $(e.target).is('a') ) {
				$(this).collapse('hide');
			}
		});

		$('.navbar-nav>li>a, .flecha>a').on('click', function(e){
			e.preventDefault();
			var target= $(e.target.hash);
			$('html, body').stop().animate({
				scrollTop: target.offset().top
			}, 1000);	

		});


	</script>
</body>
</html>

app/views/ruby_win_sources/_form.html.erb
<%= form_for(@ruby_win_source) do |f| %>
  <% if @ruby_win_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ruby_win_source.errors.count, "error") %> prohibited this ruby_win_source from being saved:</h2>

      <ul>
      <% @ruby_win_source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ruby_win_sources/edit.html.erb
<h1>Editing Ruby Win Source</h1>

<%= render 'form' %>

<%= link_to 'Show', @ruby_win_source %> |
<%= link_to 'Back', ruby_win_sources_path %>

app/views/ruby_win_sources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ruby Win Sources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th> author</th>
      <th> url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ruby_win_sources.each do |ruby_win_source| %>
      <tr>
        <td><%= ruby_win_source.name %></td>
        <td><%= ruby_win_source. author %></td>
        <td><%= ruby_win_source. url %></td>
        <td><%= link_to 'Show', ruby_win_source %></td>
        <td><%= link_to 'Edit', edit_ruby_win_source_path(ruby_win_source) %></td>
        <td><%= link_to 'Destroy', ruby_win_source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ruby win source', new_ruby_win_source_path %>

app/views/ruby_win_sources/new.html.erb
<h1>New Ruby Win Source</h1>

<%= render 'form' %>

<%= link_to 'Back', ruby_win_sources_path %>

app/views/ruby_win_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ruby_win_source.name %>
</p>

<p>
  <strong> author:</strong>
  <%= @ruby_win_source. author %>
</p>

<p>
  <strong> url:</strong>
  <%= @ruby_win_source. url %>
</p>

<%= link_to 'Edit', edit_ruby_win_source_path(@ruby_win_source) %> |
<%= link_to 'Back', ruby_win_sources_path %>

app/views/welcome/index.html.erb
<!-- Navbar -->
<nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Ramón Ledezma</a>
		</div>
		<div class="collapse navbar-collapse nav-spy" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li><a class="spythis" href="#about">ABOUT</a></li>
				<li><a class="spythis" href="#services">SERVICES</a></li>
				<li><a class="spythis" href="#portfolio">PORTFOLIO</a></li>
				<li><a class="spythis" href="#contact">CONTACT</a></li>
			</ul>
		</div>
	</div>
</nav>

<!-- Intro -->
<header>
	<div class="container">
		<div class="presentation">
			<div class="title-name">Welcome, I am<br>
				Ramón Ledezma</div>
				<div class="intro-text">IT Engineer, Full Stack Web Developer</div>
				<div class="fa-5x text-center">
					<a class="flecha" href="#services"><span class="text-center fa fa-chevron-down"></span></a>
				</div>
			</div>


		</div>
	</header>
	<!-- End Intro -->


	<span id="about" style="display:block"></span>
	<!-- Start About Section -->
	<section class="about">
		<div class="container-fluid">
			<h1 class="page-header text-center">ABOUT ME</h1>
			<h3 class="text-center text-muted about-subtitle"><em class="page-subtitle">A Brief Introduction</em></h3>
			<div class="row">
				<div class="col-sm-4">
					<img class="img-responsive img-circle" src="http://i63.tinypic.com/2ylmrf7.jpg" alt="" />
				</div>
				<div class="col-sm-8">
					<p class="text-justify">My name is Ramón Emilio Ledezma Vargas, I'm a graduate engineer from Venezuela. Since I was a child I was tied to computers and my dream was to make it my job somehow. In order to achieve that goal I enrolled into college to study IT Engineering, where I learnt programming and advanced computer science skills that helped complete the challenges that came ahead. I've been offered a variety of projects which thanks to the education  received and a lot of self learning I was capable of being to the height of the tasks. Learning is a never ending process and there's nothing more satisfiying than acquiring knowledge and working on things that you really enjoy.</p>

				</div>
			</div>
		</div>
	</section>
	<!-- End About Section -->
	<span id="services" style="display:block"></span>
	<!-- Services Section -->
	<section class="services" >
		<div class="container-fluid">

			<h1  class="text-center page-header" >SERVICES</h1>
			<h3 class="text-muted text-center services-subtitle "><em class="page-subtitle">Wanting to land your feet on the web? We got you covered.</em></h3>

			<div class="row services-list text-center">
				<div class="col-sm-3">
					<div class="fa-5x">
						<i class="fa fa-money"></i>
					</div>
					<h3 class="service-title">E-Commerce</h3>
					<p class="text-muted">Take your business to the next level, if you sell something and it's not online, you're losing money!</p>
				</div>
				<div class="col-sm-3">
					<div class="fa-5x">
						<i class="fa fa-laptop"></i>
					</div>
					<h3 class="service-title">Responsive Design</h3>
					<p class="text-muted">Be on all devices, your webpage will look beatiful on your smartphone as in your desktop computer.</p>
				</div>
				<div class="col-sm-3">
					<div class="fa-5x">
						<i class="fa fa-code"></i>
					</div>
					<h3 class="service-title">Modern Technologies</h3>
					<p class="text-muted">IT grows every second that passes by. Get always the lastest technologies and be part of that growth.</p>

				</div>
				<div class="col-sm-3">
					<div class="fa-5x">
						<i class="fa fa-rss"></i>
					</div>
					<h3 class="service-title">Social Media</h3>
					<p class="text-muted">Be present on all devices, your webpage will look beatiful on your smartphone as in your desktop computer. </p>
				</div>
			</div>
		</section>
		<!--End Services Section -->
		<span id="portfolio" style="display:block"></span>
		<!--Start Portfolio Section -->
		<section class="portfolio">
			<div class="container-fluid">
				<h1 class="text-center page-header">PORTFOLIO</h1>
				<h3 class="text-muted text-center portfolio-subtitle"><em class="page-subtitle">Some creations right out of the lab.</em></h3>
				<div class="row text-center">
					<div class="col-sm-6 col-md-3">
						<a class="portfolio-link" href="http://www.palacehotel.com.ve" target="_blank">
							<div class="icon-hover">
								<div class="hover-content">
									<i class="link-icon fa fa-link fa-4x"></i>
								</div>

							</div>


									<div class="thumbnail">
										<img src="/images/palace-thumb2.jpg">
									</div>

						</a>
								<div class="port-caption">
									<h3>Palace Hotel</h3>
									<h4 class="text-muted">Website design and booking system.</h4>
								</div>





					</div>
					<div class="col-sm-6 col-md-3">
						<a class="portfolio-link" href="http://www.repuestoslosgallegos.com.ve" target="_blank">
							<div class="icon-hover">
								<div class="hover-content">
									<i class="link-icon fa fa-link fa-4x"></i>
								</div>

							</div>
								<div class="thumbnail">

									<img src="/images/repuestos-thumb.jpg">


								</div>


						</a>

							<h3>Repuestos Los Gallegos</h3>
							<h4 class="text-muted">Website design and minimalistic online store.</h4>




					</div>
					<div class="col-sm-6 col-md-3">
						<a class="portfolio-link" href="http://www.diluga.com.ve" target="_blank">
							<div class="icon-hover">
								<div class="hover-content">
									<i class="link-icon fa fa-link fa-4x"></i>
								</div>

							</div>
								<div class="thumbnail">

									<img src="/images/dilugathumb.jpg">
								</div>
							</a>

								<h3>Dist. de Lubricantes Los Gallegos</h3>
								<h4 class="text-muted">Website design.</h4>
					</div>


					<div class="col-sm-6 col-md-3">
						<a href="#">
							<div class="icon-hover">
								<div class="hover-content">
									<i class="link-icon fa fa-link fa-4x"></i>
								</div>

							</div>

								<div class="thumbnail">

									<img src="/images/placeholder.png">
								</div>

						</a>
								<h3>Mercality LLC</h3>
								<h4 class="text-muted">lorem ipsum</h4>

					</div>

				</div>

			</div>

		</section>
		<!-- End Portfolio Section -->
		<span id="contact" style=" margin-top:-60px;display:block"></span>

		<!-- Start Footer -->

		<div class="footer">
			<div class="nav navbar-default navbar-inverse">

				<div class="container-fluid">
					<div class="row text-center">
						<h1 class="">CONTACT</h1>

						<div class="col-sm-8">
							<form action="">
								<div class="col-sm-6">
									<div class="form-group">
										<input type="text" class="form-control" placeholder="YOUR NAME*" />
									</div>
									<div class="form-group">
										<input type="email" class="form-control" placeholder="YOUR EMAIL*" />
									</div>
									<div class="form-group ">
										<input type="text" class="form-control" placeholder="YOUR PHONE*" />
									</div>

								</div>
								<div class="col-sm-6">
									<div class="form-group">
										<textarea class="form-control" name="" id=""  placeholder="YOUR MESSAGE*"></textarea>
									</div>
								</div>

							</form>
							<div class="col-sm-12">
								<button class="btn-info btn-block text-center">SEND MESSAGE</button>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="row">
								<div class="col-xs-4 fa-5x">
									<a href="https://www.facebook.com/Mercality" target="_blank"><span class="fa fa-facebook-square"></span></a>
								</div>
								<div class="col-xs-4 fa-5x">
									<a href="https://twitter.com/lvramon" target="_blank"><span class="fa fa-twitter-square"></span></a>
								</div>
								<div class="col-xs-4 fa-5x">
									<a href="https://ve.linkedin.com/in/ramón-ledezma-30a12689" target="_blank"><span class="fa fa-linkedin-square"></span></a>
								</div>
							</div>
							<div class="row">
							<div class="fa-1x col-xs-12 text-left">
									<span class="fa fa-whatsapp"> +58 416-0350957</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="row">

				</div>
			</div>
		</div>

		<!-- End Footer -->